apiVersion: v1
kind: Service
metadata:
  name: dev-web
  labels:
    app: dev-web
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    targetPort: 8002
  selector:
    run: dev-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: dev-web
        app: dev-web
    spec:
      containers:
      - name: dev-web
        image: woojuin/dev-web
        ports:
          - containerPort: 8002
      imagePullSecrets:
        - name: rlawogns1!

